set(_CATKIN_CURRENT_PACKAGE "assigment3_turtlebot3")
set(assigment3_turtlebot3_VERSION "0.0.0")
set(assigment3_turtlebot3_MAINTAINER "atefemran <atefemran@todo.todo>")
set(assigment3_turtlebot3_PACKAGE_FORMAT "2")
set(assigment3_turtlebot3_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(assigment3_turtlebot3_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(assigment3_turtlebot3_BUILDTOOL_DEPENDS "catkin")
set(assigment3_turtlebot3_BUILDTOOL_EXPORT_DEPENDS )
set(assigment3_turtlebot3_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(assigment3_turtlebot3_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(assigment3_turtlebot3_TEST_DEPENDS )
set(assigment3_turtlebot3_DOC_DEPENDS )
set(assigment3_turtlebot3_URL_WEBSITE "")
set(assigment3_turtlebot3_URL_BUGTRACKER "")
set(assigment3_turtlebot3_URL_REPOSITORY "")
set(assigment3_turtlebot3_DEPRECATED "")